{
  parserClass="org.example.idea.lang.LangParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Lang"
  psiImplClassSuffix="Impl"
  psiPackage="org.example.idea.psi"
  psiImplPackage="org.example.idea.psi.impl"

  elementTypeHolderClass="org.example.idea.psi.LangTypes"
  elementTypeClass="org.example.idea.psi.LangElementType"
  tokenTypeClass="org.example.idea.psi.LangTokenType"

  tokens = [
    KW='kw'
    SEMI=';'
    VALID='valid'
    INVALID='invalid'
  ]
}

file ::= root
root ::= 'kw' content ';' { pin=1 }
content ::= 'valid' { recoverWhile=kw_recover }
private kw_recover ::= !';'
